apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: amazon/aws-cli
    command: 
      - sh
      - -c
      - sleep 3600
      
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
      
  serviceAccountName: testpod-sa
    
  